baseURL = 'https://lizhengda0525-sudo.github.io/'
title = '达的学习笔记'
theme = 'PaperMod'

[params]
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true
  TocOpen = false
  mainSections = ['posts']
  description = '把零散的思考，整理成可以回看的知识。'

[params.label]
  text = '达的学习笔记'

[params.cover]
  hidden = true

[languages.zh-cn]
  locale = 'zh-cn'
  label = '中文'
  weight = 1

[languages.zh-cn.menu]
  [[languages.zh-cn.menu.main]]
    name = '首页'
    url = '/'
    weight = 1
  [[languages.zh-cn.menu.main]]
    name = '归档'
    url = '/archives/'
    weight = 2
  [[languages.zh-cn.menu.main]]
    name = '分类'
    url = '/categories/'
    weight = 3
  [[languages.zh-cn.menu.main]]
    name = '标签'
    url = '/tags/'
    weight = 4
  [[languages.zh-cn.menu.main]]
    name = '搜索'
    url = '/search/'
    weight = 5
  [[languages.zh-cn.menu.main]]
    name = '关于'
    url = '/about/'
    weight = 6

[markup.highlight]
  lineNos = true
  style = 'monokai'
  anchorLineNos = false
  codeFences = true
  guessSyntax = true
  noClasses = false

[outputs]
  home = ['HTML', 'RSS', 'JSON']
